test:
	go test ./...
	cd ${PWD}/pkg/github/ && go test ./...
	cd ${PWD}/pkg/gitlab/ && go test ./...
	cd ${PWD}/pkg/repository/ && go test ./...
	cd ${PWD}/pkg/repository-slog/ && go test ./...

lint:
	golangci-lint run --fix
	cd ${PWD}/pkg/github/ && golangci-lint run --fix
	cd ${PWD}/pkg/gitlab/ && golangci-lint run --fix
	cd ${PWD}/pkg/repository/ && golangci-lint run --fix
	cd ${PWD}/pkg/repository-slog/ && golangci-lint run --fix
