name: linting

on:
  push:

jobs:
  code-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - { name: main, dir: './' }
          - { name: github, dir: './pkg/github/' }
          - { name: gitlab, dir: './pkg/gitlab/' }
          - { name: repository, dir: './pkg/repository/' }
          - { name: repository-slog, dir: './pkg/repository-slog/' }

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5

      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ${{ matrix.module.dir }}
